# Generated by Django 4.2.12 on 2024-12-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='acctive',
            new_name='active',
        ),
    ]
